### ISSUE TITLE
ComfyUI does not recognise ANY nodes after installation

### ISSUE THREAD

**Issue by LucidFir** [ForeignGods/ComfyUI-Mana-Nodes#12]
What information can I give you to help with this?

**Comment by ForeignGods** [comment]
Hey, have I understood your title correctly?
Since you installed the nodes from this repo all of you previously working custom nodes don't work anymore?
Are you using the comfyui portable standalone build for windows?
In your terminal there should be an error or additional information on what might be causing this issue.
Send me a screenshot, so I can take a look at it.

**Comment by LucidFir** [comment]
No, just the nodes related to your project.

![image](https://github.com/ForeignGods/ComfyUI-Mana-Nodes/assets/29349806/bf67f7ca-4192-44fc-aafd-f3871dd8fdcb)

![image](https://github.com/ForeignGods/ComfyUI-Mana-Nodes/assets/29349806/e8d43c40-b7ce-4a30-99f1-70ff32c7a521)

![image](https://github.com/ForeignGods/ComfyUI-Mana-Nodes/assets/29349806/82bb0da5-48be-4ee7-8cd1-3620cfc34d3b)

![image](https://github.com/ForeignGods/ComfyUI-Mana-Nodes/assets/29349806/2b6682a4-8edc-403c-a41e-236c38e49000)

**Comment by LucidFir** [comment]
![image](https://github.com/ForeignGods/ComfyUI-Mana-Nodes/assets/29349806/1da1ff7c-2e68-4dc8-8025-abc576dc8bc5)

**Comment by LucidFir** [comment]
I tried reinstalling Python, it didn't seem to help.

**Comment by ForeignGods** [comment]
> ![image](https://private-user-images.githubusercontent.com/29349806/313337055-1da1ff7c-2e68-4dc8-8025-abc576dc8bc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1OTkwOTgsIm5iZiI6MTcxMDU5ODc5OCwicGF0aCI6Ii8yOTM0OTgwNi8zMTMzMzcwNTUtMWRhMWZmN2MtMmU2OC00ZGM4LTgwMjUtYWJjNTc2ZGM4YmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE0MTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOGRkMzRmYjE0M2U2ODhiNjkxMTY2ZjVlN2E3ZGRhMmIyYjNkYTJmMTZlYmE1NzFkZjM3YmUxYWExNjI3ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H2xYqFgCO6WR4OR_t36p6Hhn12Dx_PUzDcobXqcqL3g)

This was the error you got in the terminal after queueing the prompt. (Running the workflow)
I meant to send me the import error of the nodes.
You would need to scroll to the beginning where the custom_nodes are imported after initially starting comfyui.
There should be a spesific error message.
It will most definitely be a missing library that hasn't been installed correctly to you python environment.
Feel free to send me more screenshots.
