### ISSUE TITLE
Can you give links to the model that you are using in workflow 1?

### ISSUE THREAD

**Issue by dasavatar** [ForeignGods/ComfyUI-Mana-Nodes#13]
title

**Comment by ForeignGods** [comment]
https://civitai.com/models/36538/noosphere

**Comment by ForeignGods** [comment]
https://civitai.com/models/18395/retro-anime

**Comment by ForeignGods** [comment]
https://huggingface.co//sd-controlnet-depth

**Comment by dasavatar** [comment]
hey @ForeignGods when I am trying example 2 I am not getting font list from your folder it says not in the list do u know why?

**Comment by dasavatar** [comment]
Prompt outputs failed validation
video2audio:
- Custom validation failed for node: video - Invalid video file: video/test (1).mp4
font2img:
- Value not in list: font_file: 'Akira Expanded Demo.otf' not in ['DejaVu Sans', 'DejaVu Sans Display', 'DejaVu Sans Mono', 'DejaVu Serif', 'DejaVu Serif Display', 'STIXGeneral', 'STIXNonUnicode', 'STIXSizeFiveSym', 'STIXSizeFourSym', 'STIXSizeOneSym', 'STIXSizeThreeSym', 'STIXSizeTwoSym', 'cmb10', 'cmex10', 'cmmi10', 'cmr10', 'cmss10', 'cmsy10', 'cmtt10']
-

**Comment by ForeignGods** [comment]
Yeah, we just changed the location where to fonts are loaded from.

After updating the mana nodes you should press "fix node" on the font2img node, then the system fonts should be listed.

Then you would need to add the fonts from the font_files folder to your system font for now.

I'll keep this issue open and close it after I added the font_files directory to the list of system fonts.
