### ISSUE TITLE
Error occurred when executing KSampler:

### ISSUE THREAD

**Issue by zhenyuanzhou** [ForeignGods/ComfyUI-Mana-Nodes#17]
Can anybody help? Thanks.

Error occurred when executing KSampler:

module 'comfy.sample' has no attribute 'prepare_mask'

File "F:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
res_value = old_func(*final_args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\nodes.py", line 1344, in sample
return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\nodes.py", line 1314, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\Comfyui-StableSR\nodes.py", line 69, in hook_sample
return original_sample(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 234, in motion_sample
function_injections.inject_functions(model, params)
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 181, in inject_functions
self.orig_prepare_mask = comfy.sample.prepare_mask
^^^^^^^^^^^^^^^^^^^^^^^^^
![workflow](https://github.com/ForeignGods/ComfyUI-Mana-Nodes/assets/7355407/28a86607-b88b-42ad-89a3-12d7ddf5fd02)

**Comment by ForeignGods** [comment]
It looks like there is nothing connected to the **latent_image input** on your **KSampler**.
Make sure there is an **Empty Latent Image node** connected to the **KSampler**.
To organize the workflow, I placed some nodes behind others.
Let me know if this resolved your problem.
![grafik](https://github.com/ForeignGods/ComfyUI-Mana-Nodes/assets/78089013/a0a1ba5b-31d9-413d-b284-65a354b8c552)

**Comment by ForeignGods** [comment]
Nevermind I just set the link connection mode to spline like in your screenshot.
This makes it look like there is no connection.
It has to be another problem, because if there would be no connection you would get a red outline on your KSampler since the latent_image input is required.
I'm further looking into this.

**Comment by ForeignGods** [comment]
Have you tried this solution?
https://github.com/comfyanonymous/ComfyUI/discussions/3234
