### ISSUE TITLE
IMPORT FAILED - moviepi issues

### ISSUE THREAD

**Issue by Phando** [ForeignGods/ComfyUI-Mana-Nodes#21]
Super excited to check out these nodes! I am on windows 11 running a relatively fresh version of ComfyUI embedded. I have installed directly and through the manager. I am seeing the following error when comfy boots up:

```
File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Mana-Nodes\__init__.py", line 3, in <module>
    from .nodes.video2audio_node import video2audio
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Mana-Nodes\nodes\video2audio_node.py", line 9, in <module>
    from moviepy.editor import VideoFileClip
ModuleNotFoundError: No module named 'moviepy'
```

When doing things manually I tried running the requirements with the following (with and without trusted-host):

` ..\..\..\python_embeded\python.exe -m pip install -trusted-host -r .\requirements.txt`

Per the fixes here https://github.com/lengstrom/fast-style-transfer/issues/129 I also tried moviepi directly with:
`
..\..\..\python_embeded\python.exe -m pip install --trusted-host pypi.python.org moviepy`

FFMpeg is installed and added to my system PATH so I think I am good there. 

Any help would be much appreciated

**Comment by ForeignGods** [comment]
Issue could be resolved.
Following solution from @Phando on reddit:

Just got these things working. The scheduler is awesome! Turns out i needed the -s in my python install command for moviepy
