### ISSUE TITLE
How to generate this demo image?

### ISSUE THREAD

**Issue by Datou** [ForeignGods/ComfyUI-Mana-Nodes#5]
![image](https://github.com/ForeignGods/ComfyUI-Mana-Nodes/assets/15013/0fe1c624-aeed-4537-aa4c-f549fe083fc1)

Thanks!

**Comment by ForeignGods** [comment]
I used this prompt:
`hell,flames,retro anime,sharp, best quality, masterpiece, consistent color scheme, orange and blue,`
and the same model, lora and settings like in the example_workflow1.json

**Comment by Datou** [comment]
thanks!!!
