### ISSUE TITLE
Audio node is not compatible with other extensions

### ISSUE THREAD

**Issue by Fictiverse** [ForeignGods/ComfyUI-Mana-Nodes#9]
Hello, thank you for your extension, however you are using an audio node who is not compatible with the 
[ComfyUI-VideoHelperSuite](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite) audio node one.
Is it possible to make a converision node or found a way to make both extensions compatible ?

**Comment by ForeignGods** [comment]
Just looked at the input and return types of the VHS Nodes.
It seems like it shouldn't be too difficult to make my nodes compatible with theirs.
I will further look into this when I have time.
Thanks for the feedback.

**Comment by ForeignGods** [comment]
![Screenshot 2024-03-16 at 15-44-56 ComfyUI](https://github.com/ForeignGods/ComfyUI-Mana-Nodes/assets/78089013/b34a02e2-4d79-45e7-96eb-6afe3a861c9d)

You can just use the ''Load Audio (Path)🎥🅥🅗🅢'' node and convert the audio_file from widget to input.
This will allow you to connect the audio output from the ''video2audio'' node to the ''Load Audio (Path)🎥🅥🅗🅢'' node.
After that you will be able to connect the ''Load Audio (Path)🎥🅥🅗🅢'' node to the ''Video Combine 🎥🅥🅗🅢'' node.
